### ISSUE TITLE
<Chart> is not a valid SSR component

### ISSUE THREAD

**Issue by skanel** [himynameisdave/svelte-frappe-charts#23] opened 2020-12-05 04:09 UTC
Any solution for this issue?

`<Chart> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
`

**Comment by himynameisdave** [comment] 2020-12-07 17:32
Duplicate of https://github.com/himynameisdave/svelte-frappe-charts/issues/14.

As of [`frappe-charts@1.x`](https://github.com/frappe/charts), the `<Chart />` component **can never be a valid SSR component** because it relies on the `window` object in the browser. Perhaps this will be fixed in `frappe-charts@2.x`, which is currently under development.

Regardless though, this is not an issue with this Svelte wrapper library, but is an issue in the underlying `frappe-charts` library, so I'll be closing this. Feel free to [file an issue over there](https://github.com/frappe/charts/issues/new).

**Closed by himynameisdave** 2020-12-07 17:32 UTC

**Comment by melgrove** [comment] 2021-04-12 00:50
Similar to #14, I fixed this with `npm i --save-dev svelte-frappe-charts`
